baseURL = 'https://msc.masa86.com/'
languageCode = 'ja'
title = 'masa86 Music'
theme = 'PaperMod'

[params]
  description = "éŸ³æ¥½ãƒ¬ãƒ“ãƒ¥ãƒ¼ã¨éŸ³æ¥½ã«é–¢ã™ã‚‹é›‘è¨˜"
  author = "masa86"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  defaultTheme = "auto"

[params.homeInfoParams]
  Title = "masa86 Music ğŸµ"
  Content = "éŸ³æ¥½ãƒ¬ãƒ“ãƒ¥ãƒ¼ã¨éŸ³æ¥½ã«é–¢ã™ã‚‹é›‘è¨˜ã‚’æ›¸ã„ã¦ã„ã¾ã™"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/masa162"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "è¨˜äº‹"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "ã‚¿ã‚°"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "search"
    name = "æ¤œç´¢"
    url = "/search/"
    weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    style = "monokai"
